// CUDA GPU miner implementation for Linux (NVIDIA GPUs).
//
// Uses direct FFI to libcuda.so — zero external Rust dependencies.
// This ensures compatibility with any CUDA driver version (12.x, 13.x, etc.).
//
// Performance optimizations:
//   1. Midstate precompute: CPU computes SHA-256(chunk1), GPU only does chunk2 + 2nd hash.
//   2. Double-buffered CUDA streams: keep GPU saturated while host prepares next dispatch.
//   3. Auto-tuning: block size 256, per_dispatch from SM count × 2M nonces.

use std::ffi::CString;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{mpsc, Arc, Mutex};
use std::thread;
use std::time::{Instant, SystemTime, UNIX_EPOCH};

use crate::job::{diff_to_target, hash_meets_target, MiningJob};
use crate::stratum::FoundShare;

// ─── CUDA Driver API types ─────────────────────────────────────────────

#[allow(non_camel_case_types)]
type CUresult = i32;
type CUdevice = i32;
type CUdeviceptr = u64;
type CUcontext = *mut std::ffi::c_void;
type CUmodule = *mut std::ffi::c_void;
type CUfunction = *mut std::ffi::c_void;
type CUstream = *mut std::ffi::c_void;

const CUDA_SUCCESS: CUresult = 0;

#[allow(non_camel_case_types)]
enum CUdevice_attribute {
    CU_DEVICE_ATTRIBUTE_MULTIPROCESSOR_COUNT = 16,
    CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MAJOR = 75,
    CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MINOR = 76,
}

// ─── FFI bindings to libcuda.so ────────────────────────────────────────

extern "system" {
    fn cuInit(flags: u32) -> CUresult;
    fn cuDeviceGet(device: *mut CUdevice, ordinal: i32) -> CUresult;
    fn cuDeviceGetName(name: *mut i8, len: i32, dev: CUdevice) -> CUresult;
    fn cuDeviceGetAttribute(pi: *mut i32, attrib: i32, dev: CUdevice) -> CUresult;
    fn cuCtxCreate_v2(pctx: *mut CUcontext, flags: u32, dev: CUdevice) -> CUresult;
    fn cuCtxDestroy_v2(ctx: CUcontext) -> CUresult;
    fn cuModuleLoadData(module: *mut CUmodule, image: *const std::ffi::c_void) -> CUresult;
    fn cuModuleGetFunction(
        hfunc: *mut CUfunction,
        hmod: CUmodule,
        name: *const i8,
    ) -> CUresult;
    fn cuModuleUnload(hmod: CUmodule) -> CUresult;
    fn cuMemAlloc_v2(dptr: *mut CUdeviceptr, bytesize: u64) -> CUresult;
    fn cuMemFree_v2(dptr: CUdeviceptr) -> CUresult;
    fn cuMemcpyHtoD_v2(dst: CUdeviceptr, src: *const std::ffi::c_void, bytes: u64) -> CUresult;
    fn cuMemcpyDtoH_v2(dst: *mut std::ffi::c_void, src: CUdeviceptr, bytes: u64) -> CUresult;
    fn cuStreamCreate(phStream: *mut CUstream, flags: u32) -> CUresult;
    fn cuStreamSynchronize(hStream: CUstream) -> CUresult;
    fn cuStreamDestroy_v2(hStream: CUstream) -> CUresult;
    fn cuLaunchKernel(
        f: CUfunction,
        gridDimX: u32,
        gridDimY: u32,
        gridDimZ: u32,
        blockDimX: u32,
        blockDimY: u32,
        blockDimZ: u32,
        sharedMemBytes: u32,
        hStream: CUstream,
        kernelParams: *mut *mut std::ffi::c_void,
        extra: *mut *mut std::ffi::c_void,
    ) -> CUresult;
}

// ─── Helpers ───────────────────────────────────────────────────────────

fn ts() -> String {
    let secs = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();
    let h = (secs / 3600) % 24;
    let m = (secs / 60) % 60;
    let s = secs % 60;
    format!("[{:02}:{:02}:{:02}]", h, m, s)
}

/// Compile-time embedded PTX (generated by build.rs from sha256d_kernel.cu).
fn kernel_ptx() -> &'static [u8] {
    include_bytes!(concat!(env!("OUT_DIR"), "/sha256d_kernel.ptx"))
}

// ─── GpuMiner struct ───────────────────────────────────────────────────

#[derive(Clone)]
pub struct GpuMiner {
    device_ordinal: u32,
    block_size: u32,
    per_dispatch: u32,
    #[allow(dead_code)]
    device_name: String,
    #[allow(dead_code)]
    sm_count: u32,
    /// GPU usage percentage (1-100). 100 = full throttle.
    gpu_usage: u32,
}

impl GpuMiner {
    /// Return CUDA GPUs filtered by `gpu_devices` and configured with `gpu_usage`.
    /// If `gpu_devices` is empty, all available GPUs are returned.
    pub fn new(gpu_devices: &[u32], gpu_usage: u32) -> Vec<Self> {
        let result = unsafe { cuInit(0) };
        if result != CUDA_SUCCESS {
            eprintln!("[ERROR] cuInit failed (error {}). Is the NVIDIA driver installed?", result);
            return vec![];
        }

        let gpu_usage = gpu_usage.clamp(1, 100);
        let mut devices = Vec::new();

        if gpu_devices.is_empty() {
            // All available GPUs
            for ordinal in 0..8u32 {
                if let Some(miner) = Self::try_init_device(ordinal, gpu_usage) {
                    devices.push(miner);
                }
            }
        } else {
            // Only specified GPUs
            for &ordinal in gpu_devices {
                match Self::try_init_device(ordinal, gpu_usage) {
                    Some(miner) => devices.push(miner),
                    None => eprintln!("[WARN] GPU #{} not found, skipping", ordinal),
                }
            }
        }

        if devices.is_empty() {
            eprintln!("[ERROR] No CUDA-capable GPU found matching the filter.");
        }
        devices
    }

    fn try_init_device(ordinal: u32, gpu_usage: u32) -> Option<Self> {
        unsafe {
            let mut device: CUdevice = 0;
            if cuDeviceGet(&mut device, ordinal as i32) != CUDA_SUCCESS {
                return None;
            }

            // Device name
            let mut name_bytes = [0i8; 256];
            let device_name = if cuDeviceGetName(name_bytes.as_mut_ptr(), name_bytes.len() as i32, device) == CUDA_SUCCESS {
                let bytes: Vec<u8> = name_bytes.iter().take_while(|&&b| b != 0).map(|&b| b as u8).collect();
                String::from_utf8_lossy(&bytes).to_string()
            } else {
                format!("CUDA device {}", ordinal)
            };

            // SM count
            let mut sm_count: i32 = 0;
            let ok = cuDeviceGetAttribute(
                &mut sm_count,
                CUdevice_attribute::CU_DEVICE_ATTRIBUTE_MULTIPROCESSOR_COUNT as i32,
                device,
            ) == CUDA_SUCCESS;
            let sm_count = if ok && sm_count > 0 { sm_count as u32 } else { 128 };

            // Compute capability
            let cc = {
                let (mut maj, mut min) = (0i32, 0i32);
                let r1 = cuDeviceGetAttribute(&mut maj, CUdevice_attribute::CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MAJOR as i32, device);
                let r2 = cuDeviceGetAttribute(&mut min, CUdevice_attribute::CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MINOR as i32, device);
                if r1 == CUDA_SUCCESS && r2 == CUDA_SUCCESS { (maj, min) } else { (0, 0) }
            };

            let block_size = 256u32;
            let per_dispatch = ((sm_count as u64) * (2u64 << 20))
                .max(1u64 << 22)
                .min(1u64 << 27) as u32;

            eprintln!(
                "CUDA GPU #{}: {} ({} SMs, cc={}.{})",
                ordinal, device_name, sm_count, cc.0, cc.1
            );
            eprintln!(
                "  block_size={}, per_dispatch={}M nonces",
                block_size,
                per_dispatch / 1_048_576
            );

            Some(GpuMiner { device_ordinal: ordinal, block_size, per_dispatch, device_name, sm_count, gpu_usage })
        }
    }

    /// Spawn a mining thread using this GPU.
    pub fn run(
        &self,
        current_job: Arc<Mutex<Option<MiningJob>>>,
        running: Arc<AtomicBool>,
        hashrate: Arc<Mutex<f64>>,
        share_tx: mpsc::Sender<FoundShare>,
        subscription: Arc<Mutex<Option<crate::stratum::Subscription>>>,
        difficulty: Arc<Mutex<f64>>,
    ) {
        let device_ordinal = self.device_ordinal;
        let block_size = self.block_size;
        let per_dispatch = self.per_dispatch;
        let device_name = self.device_name.clone();
        let gpu_usage = self.gpu_usage;

        thread::spawn(move || {
            let resources = match CudaCtx::new(device_ordinal) {
                Ok(r) => r,
                Err(e) => {
                    eprintln!("{} [ERROR] CUDA init: {}", ts(), e);
                    return;
                }
            };

            let mut hash_count: u64 = 0;
            let mut last_report = Instant::now();
            let mut nonce_base: u32 = 0;
            let mut extranonce2_counter: u64 = 0;

            let block_dim = block_size;
            let grid_dim = (per_dispatch + block_dim - 1) / block_dim;

            loop {
                if !running.load(Ordering::Relaxed) {
                    break;
                }

                let job_data = {
                    let guard = current_job.lock().unwrap();
                    guard.clone()
                };

                if let Some(job) = job_data {
                    let diff = *difficulty.lock().unwrap();
                    let target = diff_to_target(diff);

                    let extranonce1 = {
                        let sub = subscription.lock().unwrap();
                        sub.as_ref().map(|s| s.extranonce1.clone()).unwrap_or_default()
                    };

                    extranonce2_counter = extranonce2_counter.wrapping_add(1);
                    let extranonce2 = {
                        let bytes = extranonce2_counter.to_le_bytes();
                        hex::encode(bytes)
                    };

                    let merkle_root = {
                        let coinbase = job.build_coinbase(&extranonce1, &extranonce2);
                        job.compute_merkle_root(&coinbase)
                    };
                    let ntime = {
                        let job_ntime = u32::from_str_radix(&job.ntime, 16).unwrap_or(0);
                        let now = SystemTime::now()
                            .duration_since(UNIX_EPOCH)
                            .unwrap_or_default()
                            .as_secs() as u32;
                        std::cmp::max(job_ntime, now)
                    };
                    let header = job.build_header(&merkle_root, ntime, 0);

                    let midstate = compute_midstate(&header);
                    let tail_words = [
                        u32::from_be_bytes([header[64], header[65], header[66], header[67]]),
                        u32::from_be_bytes([header[68], header[69], header[70], header[71]]),
                        u32::from_be_bytes([header[72], header[73], header[74], header[75]]),
                    ];
                    let target_be: [u32; 8] = std::array::from_fn(|i| {
                        let o = i * 4;
                        u32::from_be_bytes([target[o], target[o + 1], target[o + 2], target[o + 3]])
                    });

                    // Copy data to GPU
                    resources.copy_midstate(&midstate);
                    resources.copy_tail(&tail_words);
                    resources.copy_target(&target_be);
                    resources.reset_flags();

                    // Run GPU search with double-buffered streams
                    let batch_start = Instant::now();
                    let result = resources.search(
                        nonce_base,
                        per_dispatch as u64,
                        block_dim,
                        grid_dim,
                    );

                    match result {
                        Ok((found_nonce, checked)) => {
                            hash_count += checked;

                            if let Some(nonce) = found_nonce {
                                let verify_header = job.build_header(&merkle_root, ntime, nonce);
                                let hash = crate::job::double_sha256(&verify_header);
                                if hash_meets_target(&hash, &target) {
                                    eprintln!(
                                        "{} \x1b[33m✔ GPU #{} FOUND SHARE!\x1b[0m nonce={:08x} hash={}",
                                        ts(), device_ordinal, nonce, hex::encode(hash)
                                    );
                                    let _ = share_tx.send(FoundShare {
                                        job_id: job.job_id.clone(),
                                        extranonce2: extranonce2.clone(),
                                        ntime: format!("{:08x}", ntime),
                                        nonce,
                                    });
                                } else {
                                    eprintln!(
                                        "{} [WARN] GPU #{} false positive nonce={:08x}",
                                        ts(), device_ordinal, nonce
                                    );
                                }
                            }
                        }
                        Err(e) => {
                            eprintln!("{} [ERROR] GPU #{}: {}", ts(), device_ordinal, e);
                        }
                    }

                    nonce_base = nonce_base.wrapping_add(per_dispatch);

                    // ── GPU usage throttle ─────────────────────────────────
                    if gpu_usage < 100 {
                        // Sleep proportionally to reduce GPU utilization.
                        // For gpu_usage=50, sleep as long as the batch took.
                        let batch_us = batch_start.elapsed().as_micros() as u64;
                        let sleep_us = batch_us * (100 - gpu_usage as u64) / gpu_usage as u64;
                        if sleep_us > 0 {
                            thread::sleep(std::time::Duration::from_micros(sleep_us));
                        }
                    }

                    let elapsed = last_report.elapsed().as_secs_f64();
                    if elapsed >= 10.0 {
                        let hr = hash_count as f64 / elapsed;
                        *hashrate.lock().unwrap() = hr;
                        eprintln!(
                            "{} GPU #{} ({}) {:.2} MH/s",
                            ts(), device_ordinal, device_name, hr / 1_000_000.0
                        );
                        hash_count = 0;
                        last_report = Instant::now();
                    }
                } else {
                    thread::sleep(std::time::Duration::from_millis(100));
                }
            }
        });
    }
}

// ─── CUDA resource wrapper ─────────────────────────────────────────────

/// Owns a CUDA context + module + buffers + streams for one device.
struct CudaCtx {
    _context: CUcontext,
    _module: CUmodule,
    kernel: CUfunction,
    mid_buf: CUdeviceptr,
    tail_buf: CUdeviceptr,
    tgt_buf: CUdeviceptr,
    flag_buf: [CUdeviceptr; 2],
    nonce_buf: [CUdeviceptr; 2],
    hash_buf: [CUdeviceptr; 2],
    stream_a: CUstream,
    stream_b: CUstream,
}

impl CudaCtx {
    fn new(ordinal: u32) -> Result<Self, String> {
        unsafe {
            let mut device: CUdevice = 0;
            if cuDeviceGet(&mut device, ordinal as i32) != CUDA_SUCCESS {
                return Err(format!("device {} not found", ordinal));
            }

            let mut context: CUcontext = std::ptr::null_mut();
            if cuCtxCreate_v2(&mut context, 0, device) != CUDA_SUCCESS {
                return Err("cuCtxCreate failed".into());
            }

            // Load PTX with null terminator
            let ptx = kernel_ptx();
            let mut ptx_null = ptx.to_vec();
            ptx_null.push(0);
            let mut module: CUmodule = std::ptr::null_mut();
            if cuModuleLoadData(&mut module, ptx_null.as_ptr() as *const std::ffi::c_void) != CUDA_SUCCESS {
                cuCtxDestroy_v2(context);
                return Err("cuModuleLoadData failed".into());
            }

            let mut kernel: CUfunction = std::ptr::null_mut();
            let name = CString::new("sha256d_search").unwrap();
            if cuModuleGetFunction(&mut kernel, module, name.as_ptr()) != CUDA_SUCCESS {
                cuModuleUnload(module);
                cuCtxDestroy_v2(context);
                return Err("cuModuleGetFunction failed".into());
            }

            macro_rules! alloc {
                ($bytes:expr) => {{
                    let mut p: CUdeviceptr = 0;
                    if cuMemAlloc_v2(&mut p, $bytes) != CUDA_SUCCESS {
                        return Err(format!("alloc {}B failed", $bytes));
                    }
                    p
                }};
            }

            macro_rules! stream {
                () => {{
                    let mut s: CUstream = std::ptr::null_mut();
                    if cuStreamCreate(&mut s, 0) != CUDA_SUCCESS {
                        return Err("cuStreamCreate failed".into());
                    }
                    s
                }};
            }

            Ok(CudaCtx {
                _context: context,
                _module: module,
                kernel,
                mid_buf: alloc!(32),
                tail_buf: alloc!(12),
                tgt_buf: alloc!(32),
                flag_buf: [alloc!(4), alloc!(4)],
                nonce_buf: [alloc!(4), alloc!(4)],
                hash_buf: [alloc!(32), alloc!(32)],
                stream_a: stream!(),
                stream_b: stream!(),
            })
        }
    }

    fn copy_midstate(&self, data: &[u32; 8]) {
        unsafe { cuMemcpyHtoD_v2(self.mid_buf, data.as_ptr() as _, 32); }
    }

    fn copy_tail(&self, data: &[u32; 3]) {
        unsafe { cuMemcpyHtoD_v2(self.tail_buf, data.as_ptr() as _, 12); }
    }

    fn copy_target(&self, data: &[u32; 8]) {
        unsafe { cuMemcpyHtoD_v2(self.tgt_buf, data.as_ptr() as _, 32); }
    }

    fn reset_flags(&self) {
        let zero: u32 = 0;
        unsafe {
            cuMemcpyHtoD_v2(self.flag_buf[0], &zero as *const _ as _, 4);
            cuMemcpyHtoD_v2(self.flag_buf[1], &zero as *const _ as _, 4);
        }
    }

    /// Run double-buffered GPU search. Returns (found_nonce, total_checked).
    fn search(
        &self,
        start_nonce: u32,
        total_count: u64,
        block_dim: u32,
        grid_dim: u32,
    ) -> Result<(Option<u32>, u64), String> {
        unsafe {
            let mut committed: u64 = 0;
            let mut done: u64 = 0;
            let mut slot: usize = 0;
            let streams = [self.stream_a, self.stream_b];
            let mut prev: Option<(CUstream, usize, u64)> = None;
            let mut found: Option<u32> = None;

            while committed < total_count {
                let left = total_count - committed;
                let batch = left.min(u32::MAX as u64) as u32;
                let batch_start = start_nonce.wrapping_add(committed as u32);

                self.launch(batch_start, batch as u64, grid_dim, block_dim, slot, streams[slot])?;
                committed += batch as u64;

                if let Some((prev_stream, prev_slot, prev_batch)) = prev.take() {
                    cuStreamSynchronize(prev_stream);
                    done += prev_batch;

                    let mut flag: u32 = 0;
                    cuMemcpyDtoH_v2(&mut flag as *mut _ as _, self.flag_buf[prev_slot], 4);
                    if flag != 0 {
                        let mut nonce: u32 = 0;
                        cuMemcpyDtoH_v2(&mut nonce as *mut _ as _, self.nonce_buf[prev_slot], 4);
                        found = Some(nonce);
                        cuStreamSynchronize(streams[slot]);
                        done += batch as u64;
                        break;
                    }
                }

                prev = Some((streams[slot], slot, batch as u64));
                slot = 1 - slot;
            }

            if found.is_none() {
                if let Some((prev_stream, prev_slot, prev_batch)) = prev.take() {
                    cuStreamSynchronize(prev_stream);
                    done += prev_batch;

                    let mut flag: u32 = 0;
                    cuMemcpyDtoH_v2(&mut flag as *mut _ as _, self.flag_buf[prev_slot], 4);
                    if flag != 0 {
                        let mut nonce: u32 = 0;
                        cuMemcpyDtoH_v2(&mut nonce as *mut _ as _, self.nonce_buf[prev_slot], 4);
                        found = Some(nonce);
                    }
                }
            }

            Ok((found, done))
        }
    }

    unsafe fn launch(
        &self,
        start_nonce: u32,
        total_nonces: u64,
        grid_dim: u32,
        block_dim: u32,
        slot: usize,
        stream: CUstream,
    ) -> Result<(), String> {
        let args: [*mut std::ffi::c_void; 8] = [
            &self.mid_buf as *const _ as _,
            &self.tail_buf as *const _ as _,
            &self.tgt_buf as *const _ as _,
            &start_nonce as *const _ as _,
            &self.flag_buf[slot] as *const _ as _,
            &self.nonce_buf[slot] as *const _ as _,
            &self.hash_buf[slot] as *const _ as _,
            &total_nonces as *const _ as _,
        ];

        let r = cuLaunchKernel(
            self.kernel,
            grid_dim, 1, 1,
            block_dim, 1, 1,
            0, stream,
            args.as_ptr() as *mut _,
            std::ptr::null_mut(),
        );

        if r != CUDA_SUCCESS {
            Err(format!("cuLaunchKernel failed: {}", r))
        } else {
            Ok(())
        }
    }
}

impl Drop for CudaCtx {
    fn drop(&mut self) {
        unsafe {
            cuMemFree_v2(self.mid_buf);
            cuMemFree_v2(self.tail_buf);
            cuMemFree_v2(self.tgt_buf);
            for &b in &self.flag_buf { cuMemFree_v2(b); }
            for &b in &self.nonce_buf { cuMemFree_v2(b); }
            for &b in &self.hash_buf { cuMemFree_v2(b); }
            cuStreamDestroy_v2(self.stream_a);
            cuStreamDestroy_v2(self.stream_b);
            cuModuleUnload(self._module);
            cuCtxDestroy_v2(self._context);
        }
    }
}

// ─── CPU midstate computation ──────────────────────────────────────────

fn compute_midstate(header: &[u8; 80]) -> [u32; 8] {
    let k: [u32; 64] = [
        0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4,
        0xab1c5ed5, 0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe,
        0x9bdc06a7, 0xc19bf174, 0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f,
        0x4a7484aa, 0x5cb0a9dc, 0x76f988da, 0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7,
        0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967, 0x27b70a85, 0x2e1b2138, 0x4d2c6dfc,
        0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85, 0xa2bfe8a1, 0xa81a664b,
        0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070, 0x19a4c116,
        0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
        0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7,
        0xc67178f2,
    ];

    let mut w = [0u32; 64];
    for i in 0..16 {
        w[i] = u32::from_be_bytes([
            header[i * 4],
            header[i * 4 + 1],
            header[i * 4 + 2],
            header[i * 4 + 3],
        ]);
    }
    for i in 16..64 {
        let s0 = w[i - 15].rotate_right(7) ^ w[i - 15].rotate_right(18) ^ (w[i - 15] >> 3);
        let s1 = w[i - 2].rotate_right(17) ^ w[i - 2].rotate_right(19) ^ (w[i - 2] >> 10);
        w[i] = w[i - 16].wrapping_add(s0).wrapping_add(w[i - 7]).wrapping_add(s1);
    }

    let mut h: [u32; 8] = [
        0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab,
        0x5be0cd19,
    ];

    let mut a = h[0];
    let mut b = h[1];
    let mut c = h[2];
    let mut d = h[3];
    let mut e = h[4];
    let mut f = h[5];
    let mut g = h[6];
    let mut hh = h[7];

    for i in 0..64 {
        let s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
        let ch = (e & f) ^ ((!e) & g);
        let t1 = hh.wrapping_add(s1).wrapping_add(ch).wrapping_add(k[i]).wrapping_add(w[i]);
        let s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
        let maj = (a & b) ^ (a & c) ^ (b & c);
        let t2 = s0.wrapping_add(maj);
        hh = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
    }

    h[0] = h[0].wrapping_add(a);
    h[1] = h[1].wrapping_add(b);
    h[2] = h[2].wrapping_add(c);
    h[3] = h[3].wrapping_add(d);
    h[4] = h[4].wrapping_add(e);
    h[5] = h[5].wrapping_add(f);
    h[6] = h[6].wrapping_add(g);
    h[7] = h[7].wrapping_add(hh);

    h
}
